---
# Elasticsearch Ansible Variables

elasticsearch_user: elasticsearch
elasticsearch_group: elasticsearch
elasticsearch_download_url: https://download.elasticsearch.org/elasticsearch/elasticsearch
elasticsearch_apt_repos:
  - 'ppa:webupd8team/java'
elasticsearch_apt_dependencies:
  - htop
  - ntp
  - unzip
elasticsearch_home_dir: /usr/share/elasticsearch
elasticsearch_plugin_dir: /usr/share/elasticsearch/plugins
elasticsearch_log_dir: /var/log/elasticsearch
elasticsearch_data_dir: /var/lib/elasticsearch
elasticsearch_work_dir: /tmp/elasticsearch
elasticsearch_conf_dir: /etc/elasticsearch
elasticsearch_service_startonboot: no
#elasticsearch_http_cors_enabled: "false"
elasticsearch_service_state: started

# Non-Elasticsearch Defaults
apt_cache_valid_time: 300 # seconds between "apt-get update" calls.

elasticsearch_version: 1.7.0
elasticsearch_apt_java_package: oracle-java8-installer
elasticsearch_java_home: /usr/lib/jvm/java-8-oracle
elasticsearch_heap_size: 1g
elasticsearch_max_open_files: 65535
elasticsearch_node_max_local_storage_nodes: 1
elasticsearch_index_mapper_dynamic: "true"
elasticsearch_memory_bootstrap_mlockall: "true"
elasticsearch_install_java: "true"
elasticsearch_plugins:
  - {name: 'elasticsearch/elasticsearch-analysis-kuromoji/2.7.0'}
elasticsearch_thread_pools:
  - "threadpool.bulk.type: fixed"
  - "threadpool.bulk.size: 50"
  - "threadpool.bulk.queue_size: 1000"
