- name: Import GPG keys
  become_user: deploy
  become: yes
  shell: 'gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3'

- name: Install curl
  apt: name=curl state=latest

- name: Install RVM
  become_user: deploy
  become: yes
  shell: 'curl -sSL https://get.rvm.io | bash -s stable'

- name: Install rubies
  become_user: deploy
  become: yes
  shell: bash -lc 'rvm install {{ruby_version}}'
