- name: Create user
  user:
    name: deploy
    password: ''
    shell: /bin/bash
    state: present
    append: yes
    groups: sudo

- name: Nopassword
  lineinfile: "dest=/etc/sudoers backup=yes state=present regexp='^deploy' line='deploy ALL=(ALL) NOPASSWD: ALL'"
